<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>

  <ItemGroup Label="Direct package versions">
    <PackageVersion Include="Avalonia" Version="12.0.5" />
    <PackageVersion Include="Avalonia.Controls.WebView" Version="12.0.1" />
    <PackageVersion Include="Avalonia.Desktop" Version="12.0.5" />
    <PackageVersion Include="Avalonia.Themes.Fluent" Version="12.0.5" />
    <PackageVersion Include="GitVersion.MsBuild" Version="6.8.2" />
  </ItemGroup>
</Project>
